[build]
builder = "dockerfile"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port 7777 --log-level debug"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 15
restartPolicyType = "on_failure"

[env]
PYTHONUNBUFFERED = "1"