[build]
builder = "dockerfile"

[deploy]
startCommand = "python cookbook/playground/demo.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 15
healthcheckGracePeriod = 60
restartPolicyType = "on_failure"

[env]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
EXA_API_KEY = "${EXA_API_KEY}"
DALLE_API_KEY = "${OPENAI_API_KEY}"
DATABASE_URL = "sqlite:///tmp/agents.db" 