[build]
builder = "dockerfile"

[deploy]
startCommand = "/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 15
restartPolicyType = "on_failure"

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"