PYTHONPATH_ENV_VAR: str = "PYTHONPATH"
PHI_RUNTIME_ENV_VAR: str = "PHI_RUNTIME"

SCRIPTS_DIR_ENV_VAR: str = "PHI_SCRIPTS_DIR"
STORAGE_DIR_ENV_VAR: str = "PHI_STORAGE_DIR"
WORKSPACE_ROOT_ENV_VAR: str = "PHI_WORKSPACE_ROOT"
